import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Landing from '@/comps/Landing/Landing'
import Service from '@/comps/Landing/Service'
import About from '@/comps/Landing/About'
import Testomonial from '@/comps/Landing/Testomonial'
import Footer from '@/comps/Landing/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Advanceble Multimedia | Home</title>
        <meta name="description" content="Generated by Advanceble Multimedia | Home" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
      <Service />
      <Testomonial />
      <About />
      <Footer />

    </>
  )
}
