import Head from 'next/head'
import React, { useEffect } from 'react'
import { Inter } from '@next/font/google'
import Landing from '@/comps/Landing/Landing'
import Service from '@/comps/Landing/Service'
import About from '@/comps/Landing/About'
import Testomonial from '@/comps/Landing/Testomonial'
import Footer from '@/comps/Landing/Footer'
import Contact from '@/comps/COntact/Contact'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  var [loading, setLoading] = React.useState(true)
  useEffect(() => {
    setTimeout(() => {
      setLoading(false)
    }, 1000)
  }, [])
  return (
    <>
      <Head>
        <title>Advanceble Multimedia | Home</title>
        <meta name="description" content="Generated by Advanceble Multimedia | Home" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(!loading) && <>
        <Landing />
        <Service />
        <Testomonial />
        <Contact />
        <About />
        <Footer />
      </>}
      {(loading) &&
        <div className="Loading">
          <img src="https://i.ibb.co/pPFrPqq/ARTVERSE-2.gif" alt="Loading Animation" border="0" />
        </div>
      }

    </>
  )
}
